name: Chris Rossen
favicon: null
layout_spectrum: 0.48397
typography_spectrum: 0.19558
title: Chris Rossen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060107'
    - '#f4f2f5'
    - '#bdb6a6'
    - '#675237'
    - '#8c74e6'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
